kind: Secret
apiVersion: v1
metadata:
  name: basic-user-pass
  namespace: default
  uid: 862740e2-4f39-4c50-b117-05b92891d31d
  resourceVersion: '68441359'
  creationTimestamp: '2025-08-19T14:54:47Z'
  annotations:
    tekton.dev/git-0: 'https://github.com'
  managedFields:
    - manager: Mozilla
      operation: Update
      apiVersion: v1
      time: '2025-08-19T15:20:25Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:data':
          .: {}
          'f:password': {}
          'f:username': {}
        'f:metadata':
          'f:annotations':
            .: {}
            'f:tekton.dev/git-0': {}
        'f:type': {}
data:
  password: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  username: xxxxxxxxxxxxxxxxxxxxx
type: kubernetes.io/basic-auth
